### ISSUE TITLE
Problem in making it work

### ISSUE THREAD

**Issue by grebar** [sicknesz/midea-inventor-card#1]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
- midea-humidifier-card.js
- midea-humidifier-card-7dfbb60b.js
 - midea-humidifier-card-editor-8fd902ee.js

**Last working release (if known):**

**Browser and Operating System:**
- Microsoft Edge Ver. 96.0.1054.62
- Home Assistant 2021.12.5

**Description of problem:**
Hi,
first of all thank you for your fantastic card!
I just tried to install it for my new Inventor dehumidifier configured in hass throuh @nbogojevic homeassistant-midea-dehumidifier-lan.

Initially, I encountered some problem during the installation and I fix them as specified below
<b>Step 1</b>
Replaced source URLs with:

- wget https://raw.githubusercontent.com/sicknesz/midea-inventor-card/master/dist/midea-humidifier-card.js
- wget https://raw.githubusercontent.com/sicknesz/midea-inventor-card/master/dist/midea-humidifier-card-7dfbb60b.js
- wget https://raw.githubusercontent.com/sicknesz/midea-inventor-card/master/dist/midea-humidifier-card-editor-8fd902ee.js

<b>Step 2</b>
I linked the resources through the new panel in:
- Configuration / Dashboards / Resources

<b>Step 3</b>
Replaced "_XYZ" with ""

Finally I added the card in my hass but nothing happens, no card appears nor error in the log.
Have you any idea?
Thank you!

**Comment by sicknesz** [comment]
Retry today, i've updated the installation instruction btw this is supposed to be still in progress, i haven't released the card yet, if you still have issue with the new instructions (single file to download + it will self configure itself in lovelace) 
Please report again, i'll try to help you set it up.

**Comment by sicknesz** [comment]
As you did not report any more issue i assume you tried the latest version and had no issue, im closing this now.

**Comment by grebar** [comment]
> Retry today, i've updated the installation instruction btw this is supposed to be still in progress, i haven't released the card yet, if you still have issue with the new instructions (single file to download + it will self configure itself in lovelace) Please report again, i'll try to help you set it up.

Sorry for my late answer. Today I just tried to reinstall and it appears to work. Thank you!
