### ISSUE TITLE
Not loading Card

### ISSUE THREAD

**Issue by e2m32** [sicknesz/midea-inventor-card#10]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
v1.0.7
**Last working release (if known):**
NA
**Browser and Operating System:**
Chrome Version 103.0.5060.134 (Official Build) (64-bit)
Windows 10
**Home Assistant Version**
Home Assistant 2022.8.1
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220802.0 - latest

**Description of problem:**
Installed via HACS: Integration version: 1.26.2 ; Frontend version:  20220714083628
Shows up as an option and auto-configures itself to my Midea dehumidifier. No display. It acts like it is not loading the `midea-humidifier-card.js` javascript. I tried manually installing the resource by downloading manually and loading it in `/config/www`. Still not loading after multiple reboots and refreshes (F5) and wiping browser cache. Also checked in Home Assistant App for Android.

</body>
</html>

**Javascript errors shown in the web inspector (if applicable):**

```
 midea-humidifier-card  1.0.7
midea-humidifier-card.js:1  midea-humidifier-card  1.0.7
midea:1 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "midea-humidifier-card" has already been used with this registry
alarmo-card.js?hacstag=391372854141:880   ALARMO-CARD    Version: v1.4.1 
mini-graph-card-bundle.js?hacstag=1512800620110:1  MINI-GRAPH-CARD  0.11.0 
mini-climate-card-bundle.js?hacstag=268163975221:1  MINI-CLIMATE-CARD  v2.2.1 
browser_mod.js:145 BROWSER_MOD 1.5.3 IS INSTALLED    DeviceID: 9d45784e-96dd0c29
2midea-humidifier-card.js?hacstag=443842068108:125 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'state')
    at Ft.render (midea-humidifier-card.js?hacstag=443842068108:125:51)
    at Ft.update (midea-humidifier-card.js?hacstag=443842068108:1:18065)
    at Ft.performUpdate (midea-humidifier-card.js?hacstag=443842068108:1:9399)
    at Ft.scheduleUpdate (midea-humidifier-card.js?hacstag=443842068108:1:9046)
    at Ft._$EC (midea-humidifier-card.js?hacstag=443842068108:1:8954)
```

**Additional information:**

**Comment by e2m32** [comment]
![image](https://user-images.githubusercontent.com/10486510/183257311-64894a96-3710-4a85-9dd1-39ec1da600cf.png)

**Comment by gveloce** [comment]
Same here... Any solution??

**Comment by gsportelli** [comment]
In my case, it was not loading because it required the ion switch that my dehumidifier does not have. The ion switch should be optional as per docs, but this is not the case in the latest version.

**Comment by e2m32** [comment]
Thanks @gsportelli! I set `show_ion_toggle: false` and the card finally showed up! 😀

**Comment by gveloce** [comment]
Where exactly did you set this mate?

**Comment by e2m32** [comment]
> Where exactly did you set this mate?

in the card config: https://github.com/sicknesz/midea-humidifier-card#usage

The default is `true`, set to `false` like the example below (this is my config, note last line):
```
type: custom:midea-humidifier-card
entity: humidifier.midea_dehumidifier
fan_entity: fan.midea_dehumidifier_fan
tank_entity: binary_sensor.midea_dehumidifier_tank_full
defrost_entity: binary_sensor.midea_dehumidifier_defrosting
filter_entity: binary_sensor.midea_dehumidifier_replace_filter
humidity_entity: sensor.midea_dehumidifier_humidity
temperature_entity: sensor.midea_dehumidifier_temperature
ion_entity: switch.midea_dehumidifier_ion_mode
swap_target_and_current_humidity: true
show_ion_toggle: false
```

**Comment by gveloce** [comment]
still not loading for me :( I have added the card via HACS but when trying to add it by ADD CARD to Lovelace i am prresented all available cards except this one. Instead I see an empty card slot (no data) and a 'spiinning' wheel like the card is loading but it takes for ever.... How can I solve this? Do you need more data from my side to help troubleshoot this? TIA

**Comment by e2m32** [comment]
It's been a while since I added this, but I think I had to install it manually. If memory serves, it didn't add the resource reference correctly. Download `midea-humidifier-card.js` and put it in your `/config/www` directory. Then go to "Edit Dashboard" in your lovelace dashboard (3 dots in top right corner), then hit those 3 dots again and select "Manage Resources", then "+ ADD RESOURCE" and put in the following: `/local/midea-humidifier-card.js` and click "CREATE".
![image](https://user-images.githubusercontent.com/10486510/194567434-0404b6c2-51d0-4dbd-9619-0953567f055a.png)


You should be presented with this when searching Midea:
![image](https://user-images.githubusercontent.com/10486510/194566341-e1cc1412-cbce-429a-b249-dca1a8d672d4.png)

I have 2 because I have the one I installed via HACS and the one I installed manually. I forget what I did to get the HACS one to show up... I should have cleaned this up, but I wanted to keep it installed via HACS so I would be notified of updates.

**Comment by gveloce** [comment]
lots of thanx for the detailed info mate. Tried several times to reinstall it even manually but it has the same behavior and card is not loading. The only difference in my case (perhaps because I run a supervised instance of HA?) is that the path for /config/ www is /hacsfiles/... instead of /local/... and it is setup correctly but still no joy....I give up.  btw I am running HA version 2022.10 TIA

**Comment by e2m32** [comment]
> /hacsfiles/... instead of /local/...

the `hacsfiles/` entry is the one that wasn't working for me. I am running HA OS but supervised is very similar, your `config` directory might be named something different, but that part doesn't matter. `local/` refers to the directory that is available publicly. 

You need to create a `www` directory in the same directory as your `configuration.yaml` file. Then restart home assistant. You can test that your `www` directory is working correctly by dropping a jpg or text file in there and going to `http://<your_ha_ip:port>/local/<image.jpg>`.  [source](https://community.home-assistant.io/t/location-of-www-folder/236607), I also tested this in my supervised dev install.

Then you can put the `midea-humidifier-card.js` file in there and install the Lovelace resource as I outlined above. After adding the resource, you may need to restart home assistant again.

**Comment by James3UK** [comment]
HACS downloads it to /hacsfiles/midea-humidifier-card/midea-humidifier-card.js which worked for me.

**Comment by prclm** [comment]
> HACS downloads it to /hacsfiles/midea-humidifier-card/midea-humidifier-card.js which worked for me.

This is completely right! @sicknesz please update the readme for this

**Comment by sicknesz** [comment]
Ok, will do it this weekend.

**Comment by sicknesz** [comment]
fixed
