### ISSUE TITLE
Always shows Celsius

### ISSUE THREAD

**Issue by zSprawl** [sicknesz/midea-inventor-card#11]
**Checklist:**

- [ x ] I updated to the latest version available
- [ x ] I cleared the cache of my browser

**Release with the issue:**
Latest

**Last working release (if known):**
None

**Browser and Operating System:**
It doesn't matter

**Description of problem:**

The Celsius unit of measurement is hard coded in the javascript. I can see it on line 77 of midea-humidifier-card.js, but don't know how to setup an if/else statement to pull from HA config. It would be nice if this could display in freedom units.

https://github.com/sicknesz/midea-humidifier-card/blob/master/dist/midea-humidifier-card.js

**Javascript errors shown in the web inspector (if applicable):**

**Additional information:**

Thank you for the consideration if you've read this far.

**Comment by is343** [comment]
I opened a PR to fix this #12

**Comment by tanderson1992** [comment]
Is there a way to implement your PR, @is343, to the existing code? Is it possible to apply the diff to the .js file and not change the src/midea-humidifier-card.ts file?

**Comment by is343** [comment]
@tanderson1992 Sure, I just made a [gist](https://gist.github.com/is343/7f793c9323aed6c6520d8da898342fe3) with the distribution build file, and how/where to install it. You will also need to make a compressed `.gz` file that contains that same `.js` file into that directory. You can just read the comments of the gist.

I also added the dist file to the PR, so you can also take it directly from there

**Comment by tanderson1992** [comment]
Thank you for doing that. I was going to try updating the .js if I didn't hear back from you, but it was good to read that I also needed a .gz file and to update the cache.

**Comment by sicknesz** [comment]
Just merge the PR that fix this , closing now
