### ISSUE TITLE
[Feature request] option to hide Name

### ISSUE THREAD

**Issue by sn33ky** [sicknesz/midea-inventor-card#13]
It woukd be welcoming to hide the Name from the card. As an example, i already have the name set in another card configured.

Thanks
![Schermafbeelding 2022-12-03 121415](https://user-images.githubusercontent.com/78500/205438156-4d356307-1f45-4ce2-821c-7e735ace62eb.png)

**Comment by geolos** [comment]
try the below ;-)
name: " "

or

name: '  '
(the above needs two spaces)

**Comment by sn33ky** [comment]
> 

Yes i know that is a solution. But that creates white space. 
i think the cards size should then also be decreased in hight. because there aint a tekst annymore.

I see some examples of cards where you can hide the name and the card size also get's smaller.

**Comment by sicknesz** [comment]
added an configuration options to hide name : use :  `hide_name: true`  in the card configuration
