### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by fotis3d** [sicknesz/midea-inventor-card#15]
This is not a bug but how can we change the colors or icons and slider ?

**Comment by sicknesz** [comment]
Sorry i only see this now, i could create a version where the color come from the configuration, icons and sliders only ?

**Comment by fotis3d** [comment]
After the latest HA update somehow the colors behave strange. The sliders gets a colors but my icons not. I tried the color code using card mod but it colorizes the active icon, the slider and the name also. I do not know how to avoid the name /title color

**Comment by sicknesz** [comment]
Can confirm, i only have 2 colors still displaying out of 4, will look into it this week-end, sorry everyone for the long period without updates/fixes. i mostly use gitlab now so i did not see all the notifications

**Comment by sicknesz** [comment]
Fixed in the next release
