### ISSUE TITLE
Very Buggy Stadium. not showing temperature and not showing humidity

### ISSUE THREAD

**Issue by deveylder** [sicknesz/midea-inventor-card#17]
I am not getting temp or humidity.
i use a pro breeze PB 15 EU

it is showing current humidity or when i activate swap it shows te set humidity.

It is never showing both

<img width="515" alt="Scherm­afbeelding 2023-11-13 om 11 06 59" src="https://github.com/sicknesz/midea-humidifier-card/assets/31114918/d8907cf6-a107-47a2-9839-573995fbb838">

**Comment by sicknesz** [comment]
a  pro breeze PB 15 EU ?? this card is meant to be user with the Midea/Inventor EVA dehumidifier i designed it to match my own, im sorry if it does not work properly for you, are you using [midea-beautiful-air](https://github.com/nbogojevic/midea-beautiful-air#midea-beautiful-air) ? 
I just saw they added your model to their list of supported devices, but this is an unofficial card, things must be named differently for you, what is the value of the entity if you look on the devtools ( yourhomeassistanturl/developer-tools/state) ? if i can check the source code i could maybe fix the card for your model but its a big IF i would be developping "blindly" 
mine is : 
```
min_humidity: 35
max_humidity: 85
available_modes:
  - Set
  - Smart
  - Continuous
  - Dry
humidity: 50
mode: Dry
last_error_code: 0
last_error_time: "2023-11-15T22:20:36.217639"
capabilities: "{'fan_speed': 7, 'ion': 1, 'auto': 1, 'dry_clothes': 1}"
capabilities_data: b504100201071e0201011f02010120020101ab55
error_code: 0
last_data: c80104507f7f00320000000000000000226a000000000dd67b
device_class: dehumidifier
friendly_name: Déshumidificateur_6734
supported_features: 1
```

**Comment by sicknesz** [comment]
Please answer my question so I can help you. :)

**Comment by deveylder** [comment]
I missed your answer.  Sorry about that.  I will check today

**Comment by deveylder** [comment]
<img width="404" alt="Scherm­afbeelding 2023-11-23 om 13 55 45" src="https://github.com/sicknesz/midea-humidifier-card/assets/31114918/cf9a65a8-1a02-4535-9a41-f99164df4426">

**Comment by deveylder** [comment]
Again sorry for the late response.


Bart




min_humidity: 35
max_humidity: 85
available_modes:
  - Manual
  - Continuous
  - Auto
  - Clothes-Dry
  - Shoes-Dry
humidity: 50
mode: Auto
device_class: dehumidifier
icon: mdi:air-humidifier
friendly_name: Fitness
supported_features: 1



---------------------------------------------


type: custom:midea-humidifier-card
entity: humidifier.18691697852449_humidifier
humidity_entity: sensor.18691697852449_current_humidity
temperature_entity: sensor.18691697852449_current_temperature
tank_entity: sensor.18691697852449_tank18691697852449_tank
ion_entity: switch.18691697852449_power
show_ion_toggle: true
swap_target_and_current_humidity: false
fan_entity: fan.dehumidifier_18691697852449_fan

**Comment by deveylder** [comment]
![Uploading Scherm­afbeelding 2023-11-23 om 13.55.37.png…]()

**Comment by deveylder** [comment]
<img width="599" alt="Scherm­afbeelding 2023-11-23 om 14 01 59" src="https://github.com/sicknesz/midea-humidifier-card/assets/31114918/e46df4d2-633b-4b3a-8889-d7b42148583e">

**Comment by deveylder** [comment]
<img width="404" alt="Scherm­afbeelding 2023-11-23 om 13 55 45" src="https://github.com/sicknesz/midea-humidifier-card/assets/31114918/99f403d0-fe13-4f8a-b103-9d4100603c63">

**Comment by deveylder** [comment]
<img width="1248" alt="Scherm­afbeelding 2023-11-23 om 13 55 37" src="https://github.com/sicknesz/midea-humidifier-card/assets/31114918/9e8361a8-b042-4fee-8515-7eb45ccfde74">

**Comment by deveylder** [comment]
Strange you  here upset that I didn't answer you immediately.
