### ISSUE TITLE
Additional entities

### ISSUE THREAD

**Issue by eloo** [sicknesz/midea-inventor-card#2]
Hi, 

thanks for this great card. It really makes the integration seamless to homeassistant. 
But i also have a feature request to improve the card a bit.

**Is your feature request related to a problem? Please describe.**
I have my dehumidifier "enhanced" with some external devices like a zigbee hygrometer on top and an smart plug to fully power it off if desired. Also i have a switch to enable/disable the internet access for my dehumidifer and currently i need to add this switches and sensors manually to an additional card and group them. 

Maybe your card can also carry some addional entities?

**Describe the solution you'd like**
Maybe a solution could be to add them to the 'entities' key and list all not to a icon or feature mapable entities below the feature selector in the card as a simple list? 

What do you think? Does this make sense for you?

Thanks
eloo

**Comment by sicknesz** [comment]
First Thanks for the kind word, about your requests : 

You can add entities to the list it will make the cards ui respond to state change on that entities, but im not sure how to provide such feature, what type of entities are we talking about ? (smart plug/hygrometer?)

I'm not sure i could make it work, anything would have to be coded in (like for a switch you call the "switch.toggle" service, but for a light it will be "light.turn_on" and for a plug it could be "switch.turn_on/turn_off", totally different actions) 

What you ask would require my card to have an understanding of the entities you add for it to automatically provide you with the proper behavior (sensor => show value, switch => show button, binary_sensor => show on/off, etc...) 

It would be much easier for you to just use the card in a vertical-stack with a second card handling the extra entities something like button-row-card or others ones.

Im sorry i could not provide you with a better solution.

Kind regards
