### ISSUE TITLE
Ion switch

### ISSUE THREAD

**Issue by PskNorz** [sicknesz/midea-inventor-card#3]
Hey thank you for your work and the result of the card.

I just install it and i notice than when your turn on the ION the button just change a lil to bit in Grey. 

Here in ON
![image](https://user-images.githubusercontent.com/80605468/149199084-6a1c1a30-b6d7-441d-aa50-0274317b1f06.png)

And here Off
![image](https://user-images.githubusercontent.com/80605468/149199161-125dd1cb-64d2-4289-81ff-bb7a124dcc76.png)

**Comment by sicknesz** [comment]
You're right, the color i've choosen is not coherent with the rest of the UI, i'll change it to the current mode color, will post the new version tomorrow. 
Thanks for your feedback ! :)

**Comment by sicknesz** [comment]
I've updated the repo and changed the color to match others icons. @PskNorz you can check it now

PS: im sorry i won't close issue that fast without releasing a new version first, it was a mistake on my part as it closed the communication with you which wasn't really the purpose.

**Comment by PskNorz** [comment]
Hey thanks working like a charm!

![image](https://user-images.githubusercontent.com/80605468/150012002-6a719529-0e62-4d4b-8051-0f5ffa3b0ab9.png)

**Comment by PskNorz** [comment]
Don’t worry didn’t notice it anyway, but thanks for the fix 😊


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by sicknesz** [comment]
Ok, now closing the issue :)
