### ISSUE TITLE
Fan speed control broken with integration v0.6.0

### ISSUE THREAD

**Issue by 35gh** [sicknesz/midea-inventor-card#4]
First, thank you for the great work!

v0.6.0 of the homeassistant-midea-air-appliances-lan integration has introduced a breaking change on fan speed control:

> Removed speed control for fan (preset control is still there).

As a result, fan speed control is broken:
<img width="347" alt="Capture d’écran 2022-01-29 à 00 18 31" src="https://user-images.githubusercontent.com/90415090/151634953-0708292e-1964-46e5-8ba5-d3e1105381e4.png">

Thanks!

**Comment by sicknesz** [comment]
It should not have break, i only use the preset modes ... weird, i'll try lookin into it soon.

**Comment by sicknesz** [comment]
"Removed speed control for fan (preset control is still there)." this should have no impact on my code ... anyway im taking a look at it right now (as soon as my devcontainer has finished building) and come back to this when i have some news

**Comment by sicknesz** [comment]
Ok, i see why it fails, with the 0.6 i don't get the "correct" names for the fan mode, i get "Low", "Medium", "High", instead of "Silent", "Medium", "Turbo" as written on my physical device .. Im not certain if that ain't a bug from the integration id love the check it with the author.

**Comment by sicknesz** [comment]
Fixed in the latest version v1.0.7.

![Screenshot_20220131_201326](https://user-images.githubusercontent.com/3835626/151857479-cc964ee8-2c51-4c21-ad44-fed224cfbe42.png)

**Comment by 35gh** [comment]
Brilliant, It works!

Thank you.
