### ISSUE TITLE
Add midea-humidifier-card to the Home Assistant Community Store (HACS)

### ISSUE THREAD

**Issue by 35gh** [sicknesz/midea-inventor-card#5]
Hi,

It will be good to add this custom card to the Frontend section of the [Home Assistant Community Store](https://github.com/hacs).

This will ease installation and updates.

Thanks!

**Comment by sicknesz** [comment]
I don't know how to do so :) i'll also look into it :)

**Comment by sicknesz** [comment]
Until i found how to get in contact with the guys behind HACS you can add the github repositorie as a Custom Repo, paste the address and voila, you can now install it through HACS and get updates whenever a new version is released (i hope so, not 100% certain it will work out of the box for custom repo)

![Screenshot_20220131_201524](https://user-images.githubusercontent.com/3835626/151857878-99a741da-247d-416a-953e-cba1049ee2fc.png)

**Comment by 35gh** [comment]
Wow, the custom repo does work out of the box :) Thank you!

**Comment by sicknesz** [comment]
You're welcome, im closing the issue now :) i've started to add topics to match their requirement and try to have it published but as it's derived from another card im not sure it will enter the scope of what's allowed, anyway if we get new version update as a custom repo its probably fine as well.
