### ISSUE TITLE
Horizontal Card

### ISSUE THREAD

**Issue by fotis3d** [sicknesz/midea-inventor-card#8]
A good idea would be to have an option to make this card horizontal so that it would take less space in height.

Something like the attached. Unless there is a way I do not know about. :)

![MideaCardTest](https://user-images.githubusercontent.com/42974039/158248322-e05f1833-5aa4-4d0f-a46a-4415d1d08335.jpg)

Great Work though very nice card.

**Comment by sicknesz** [comment]
never saw the card displayed this way, it should look like this
![Screenshot_20220327_175512](https://user-images.githubusercontent.com/3835626/160289851-1af1c56d-2153-4a31-a97b-ffeac014ed96.png)
What's your resolution ? maybe it's the theme you're using that's causing this, but it should not happen

**Comment by fotis3d** [comment]
No you misunderstood. This is a possible future request. The existance of a horizontal card. Since the default one in some layouts takes up a lot of vertical space. Mine looks like yours.

**Comment by sicknesz** [comment]
oh okay, i'll  try to play with it this WE and if possible i'll release a new version with a "layout: horizontal||vertical" settings for the card.

**Comment by fotis3d** [comment]
That would be awesome. I tried to split it though with grid cards but it would not work very nice .
As you see in my main dashboard for example it takes up a lot of space in height.
Therefore if there was somehow an option of a horizontal card like the above it would save a lot of space. Especially in mobile views. ;)

![2022-03-28 23_42_46-Overview – Home Assistant](https://user-images.githubusercontent.com/42974039/160484030-1eb97c71-3edd-47bd-9a7d-95b361f82a0c.jpg)
