### ISSUE TITLE
"Smart" and "Dry" modes no longer available since update to integration v0.8.10 

### ISSUE THREAD

**Issue by 35gh** [sicknesz/midea-inventor-card#9]
"Smart" and "Dry" modes are no longer available since I updated to Midea Air Appliance Lan integration v0.8.10 ("Set" and "Continuous" are still accessible). Previous public version v0.8.2 was working fine. 

I'm using Home Assistant v2022.7.3

<img width="495" alt="1" src="https://user-images.githubusercontent.com/90415090/178364203-c4b5e761-3759-4736-a5b7-c13560a424dd.png">
<img width="410" alt="2" src="https://user-images.githubusercontent.com/90415090/178364209-5cdd102f-a416-4019-8ef1-3f4790ad4ef3.png">

**Comment by Turton** [comment]
I looks like things are much worse after Midea Air Appliance Lan integration v0.8.10.  I removed the integration and re-added as a troubleshooting step.  Now this card can no longer be used or re-added.   It's gone!  It's the integration that is spectacularly broken.

**Comment by 35gh** [comment]
Issue has been fixed in integration v0.8.11.

**Comment by sicknesz** [comment]
Sorry guys I'm just seeing this.
